version: "3"  # optional since v1.27.0
services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env   
    environment:
       POSTGRES_PASSWORD: ${DB_USER_PASSWORD}

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    tmpfs: /app/tmp
    tty: true
    stdin_open: true
    env_file:
      - ./.env   
    ports:
      - 3000:3000
    depends_on:
      - db
    #environment:
    #  WEBPACKER_DEV_SERVER_HOST: webpacker 
   
     # - webpacker

 # webpacker:
 #   build: .
#  command: yarn build --watch
 #   volumes:
 #     - '.:/app'
 #   ports:
 #     - 3035:3035   
 #   environment:
 #     NODE_ENV: development
 #     RAILS_ENV: development
 #     WEBPACKER_DEV_SERVER_HOST: 0.0.0.0      

