version: '3' # optional since v1.27.0
services:
  redis:
    image: redis

  db:
    image: postgres:14-alpine
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:drop db:prepare && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      RAILS_ENV: development
      DB_HOST: db

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec sidekiq"
    depends_on:
      - web
      - db
      - redis
    env_file: .env
    environment:
      RAILS_ENV: development
      DB_HOST: db

  cypress:
    container_name: cypress-test
    build:
      context: .
      dockerfile: cypress.Dockerfile
    restart: unless-stopped
    depends_on:
      - web
    tty: true
    environment:
      - CYPRESS_baseUrl=http://192.168.99.100:3000
    command: npx cypress run
#  playwright:
#    container_name: playwright-test
#    build:
#      context: .
#      dockerfile: playwright.Dockerfile
#    restart: unless-stopped
#    depends_on:
#      - web
#    tty: true
