name: cypress

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.80.0
        with:
          ruby-version: 2.7.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3    

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0

      - name: Setup test database
        env:
          POSTGRES_HOST: localhost
          RAILS_ENV: test
          DB_USER_PASSWORD: postgres
          DB_USER: postgres
        run: |
          bundle exec rails db:prepare

      - name: Start server in the background
        env:
          DB_HOST: localhost
          RAILS_ENV: test
          POSTGRES_PASSWORD: postgres
        run: |
          bundle exec rails server &
          sleep 5 && 
          curl http://localhost:3000 -I 
           

      - name: Build and test with rspec
        env:
          DB_HOST: localhost
          RAILS_ENV: test
          POSTGRES_PASSWORD: postgres
          DB_USER: postgres
        run: |
          bundle exec rspec spec/requests

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          wait-on: 'http://localhost:3000/'
            # wait for 2 minutes for the server to respond
          wait-on-timeout: 120

      - name: Upload screenshots as artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - name: Upload videos as artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos    

      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/
           

