name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          DB_HOST: localhost
          POSTGRES_PASSWORD: postgres
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.80.0
        with:
          ruby-version: 2.7.3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Install Playwright
        run: yarn add playwright --dev   

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: |
          bundle install

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0

      - name: Setup test database
        env:
          DB_HOST: localhost
          RAILS_ENV: test
          DB_USER_PASSWORD: postgres
        run: |
          bundle exec rails db:prepare

      - name: Build and test with rspec
        env:
          DB_HOST: localhost
          RAILS_ENV: test
          DB_USER_PASSWORD: postgres
        run: |
          bundle exec rspec spec/requests

      - name: Build and test with Playwright tests
        env:
          DB_USER_PASSWORD: postgres
          DB_HOST: localhost
          RAILS_ENV: test
        run: |
          npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30 

      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/
           

